### ISSUE TITLE
在UITableViewController中使用，显示位置不在正中间

### ISSUE THREAD

**Issue by liqinghua188** [Harley-xk/Chrysan#1]
在UITableViewController中使用，显示位置不在正中间

**Comment by Harley-xk** [comment]
UITableViewController 使用 UITableView 作为默认的 view，所以 chrysan 会随着 tableView 上下滚动。
所以在 UITableViewController 中使用 Chrysan 时，为了避免出现这种情况，需要使用父视图的 Chrysan 的属性。
UITableViewController 一般配合导航视图使用，这时可以使用 navigationController.chrysan 来代替 self.chrysan。

**Comment by liqinghua188** [comment]
好滴，明白了。

**Comment by Harley-xk** [comment]
😊  感谢支持～  🙏
