### ISSUE TITLE
progress不能用啊

### ISSUE THREAD

**Issue by yuyedaidao** [Harley-xk/Chrysan#6]
progress连续调用无法正常显示

**Comment by yuyedaidao** [comment]
补充一下,调用间隔短的时候无法显示,应该是开始的动画没完成

**Comment by Harley-xk** [comment]
每次更新 HUD 时都是新建的动画对象，stopAnimation 只是停止了上次可能未执行完的动画，理论上是没有影响的。
我试了下，把 Example 项目里 ProgressExample 的计时器间隔从 0.5s 改成 0.05s，显示是正常的。
@yuyedaidao 方便提供下你连续调用 progress 的上下文代码吗？

**Comment by yuyedaidao** [comment]
![image](https://user-images.githubusercontent.com/6354958/102178330-35bb5d00-3ee0-11eb-8452-eb98011d5911.png)
注释掉"准备下载",也就是说一开始进入progress状态,就能看出问题来了

**Comment by Harley-xk** [comment]
Fixed in version 2.0.2
